### ISSUE TITLE
Partytown dependency seems broken?

### ISSUE THREAD

**Issue by stephencweiss** [jpedroschmitz/gatsby-starter-ts#575]
This is an internal dependency of Gatsby, so not sure that this is a problem with the project, but I just downloaded and tried running and got the following error. 

Any idea how to fix it?

<img width="1296" alt="Screen Shot 2022-09-03 at 3 54 33 PM" src="https://user-images.githubusercontent.com/39878535/188287436-69e60ecd-f82a-4552-a186-704e1599f70d.png">

**Comment by jpedroschmitz** [comment]
If you try to update gatsby to the latest version, does it fix the issue?

**Comment by jpedroschmitz** [comment]
I tested the latest changes I shipped to the project here, and it should work now!

Thanks for opening the issue. I'll close it for now! ❤️
