### ISSUE TITLE
Default configuration give errors in tsx imports in VSCode

### ISSUE THREAD

**Issue by alexseik** [jpedroschmitz/gatsby-starter-ts#874]
When I used the started on VSCode, the files `src/components/Title.spec.tsx` and `src/pages/index.tsx` show me an error saying _Missing file extension for..._.

I solved the issue changing the file `.eslintrc`, removing the `ignorePackages` under the property `rules -> import/extensions`. 

![image](https://github.com/jpedroschmitz/gatsby-starter-ts/assets/5929078/1ea5b7fb-41ac-4e78-abec-e5536df86470)

As eslint doc stands [here](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/extensions.md) you should use `ignorePackages` if you want to enforces the use of extensions.

**Comment by jpedroschmitz** [comment]
I can't reproduce this issue locally. Perhaps it's something with the ESLint extension you're using on VSCode.

Also, if you run `pnpm lint`, there are no errors of `Missing file extension`, so it's likely something with your VSCode.

I wouldn't recommend using this extension.
